
/**
 * THE NEURAL ARCHIVE: MASTER REGISTRY DATA
 * High-fidelity narrative shards for the Sri Lankan experience.
 */

export const ABOUT_DATA: Record<string, { EN: string, SI: string }> = {
  // Ancient
  sigiriya: { 
    EN: "Sigiriya, also known as the Lion Rock, is an ancient rock fortress located in the northern Matale District near the town of Dambulla in the Central Province, Sri Lanka. It is a site of historical and archaeological significance that is dominated by a massive column of rock nearly 200 metres (660 ft) high. According to the ancient Sri Lankan chronicle the Culavamsa, this site was selected by King Kashyapa (477 – 495 AD) for his new capital. He built his palace on the top of this rock and decorated its sides with colourful frescoes. On a small plateau about halfway up the side of this rock he built a gateway in the form of an enormous lion. The name of this place is derived from this structure — Sīhāgiri, the Lion Rock. The capital and the royal palace were abandoned after the king's death. It was used as a Buddhist monastery until the 14th century. Sigiriya today is a UNESCO listed World Heritage Site. It is one of the best preserved examples of ancient urban planning.", 
    SI: "සීගිරිය හෙවත් සිංහ පර්වතය යනු ශ්‍රී ලංකාවේ මධ්‍යම පළාතේ මාතලේ දිස්ත්‍රික්කයේ දඹුල්ල නගරයට ආසන්නව පිහිටි පැරණි ශිලා බලකොටුවකි. මෙය මීටර් 200 ක් පමණ උසැති දැවැන්ත පර්වතයක් මත ගොඩනගා ඇති ඓතිහාසික හා පුරාවිද්‍යාත්මක වටිනාකමකින් යුත් ස්ථානයකි. චූලවංශයට අනුව, ක්‍රි.ව. 477 - 495 කාලයේ රජකම් කළ කාශ්‍යප රජු විසින් සිය නව අගනුවර ලෙස මෙම ස්ථානය තෝරා ගන්නා ලදී. ඔහු පර්වතය මුදුනේ සිය මාලිගය ගොඩනැගූ අතර එහි බිත්ති අලංකාර බිතුසිතුවම් වලින් සරසන ලදී. පර්වතයේ අඩක් පමණ ඉහළට වන්නට පිහිටි කුඩා තැන්නක ඔහු දැවැන්ත සිංහයෙකුගේ ස්වරූපයෙන් යුත් ද්වාරයක් ඉදිකළේය. සීගිරිය යන නාමය ව්‍යුත්පන්න වී ඇත්තේ මෙම සිංහ රූපය නිසාය. රජුගේ මරණයෙන් පසු මෙය අතහැර දැමුණු අතර 14 වන සියවස දක්වා බෞද්ධ ආරාමයක් ලෙස භාවිතා විය. අද වන විට සීගිරිය යුනෙස්කෝ ලෝක උරුමයක් ලෙස නම් කර ඇති අතර එය ලොව පැරණි නගර නිර්මාණ ශිල්පයේ විශිෂ්ටතම උදාහරණයකි." 
  },
  ruwanwelisaya: {
    EN: "The Ruwanwelisaya is a stupa and a hemispherical structure containing relics, in Sri Lanka, considered sacred to many Buddhists all over the world. It was built by King Dutugemunu c. 140 BC, who became King of all Sri Lanka after a war in which the Chola King Elara was defeated. It is also known as 'Mahathupa', 'Swarnamali Chaitya', 'Suvarnamali Mahaceti' and 'Rathnamali Dagaba'. This is one of the 'Solosmasthana' and the 'Atamasthana'. The stupa is one of the world's tallest ancient monuments, standing at 103 m (338 ft) and with a circumference of 290 m (951 ft).",
    SI: "රුවන්වැලිසෑය යනු ශ්‍රී ලංකාවේ අනුරාධපුරයේ පිහිටි මහා ස්තූපයකි. මෙය ක්‍රි.පූ. 140 දී පමණ දුටුගැමුණු රජු විසින් ඉදිකරන ලදී. මෙය 'මහාථූප', 'ස්වර්ණමාලී චෛත්‍යය' සහ 'රත්නමාලී දාගැබ' ලෙසද හැඳින්වේ. මෙය සොළොස්මස්ථාන සහ අටමස්ථාන අතරින් එකකි. මීටර් 103 ක් උසැති මෙම ස්තූපය ලොව උසම පැරණි ස්මාරකවලින් එකකි."
  },
  "jaya-sri-maha-bodhi": {
    EN: "The Jaya Sri Maha Bodhi is a sacred fig tree in the Mahamewna Gardens, Anuradhapura, Sri Lanka. It is said to be the southern branch from the historical Sri Maha Bodhi at Buddha Gaya in India under which Lord Buddha attained Enlightenment. It was planted in 288 BC, and is the oldest living human-planted tree in the world with a known planting date. It was brought to Sri Lanka by Sangamitta Theri, daughter of Emperor Asoka and founder of an order of Buddhist nuns in Sri Lanka.",
    SI: "ජය ශ්‍රී මහා බෝධීන් වහන්සේ යනු ශ්‍රී ලංකාවේ අනුරාධපුර මහමෙව්නා උයනේ පිහිටි පූජනීය බෝධීන් වහන්සේය. මෙය බුදුරජාණන් වහන්සේ බුද්ධත්වයට පත් වූ ඉන්දියාවේ බුද්ධගයාවේ ශ්‍රී මහා බෝධීන් වහන්සේගේ දකුණු ශාඛාවක් ලෙස සැලකේ. ක්‍රි.පූ. 288 දී රෝපණය කරන ලද මෙය, රෝපණය කළ දිනයක් සහිත ලොව පැරණිතම ජීවමාන වෘක්ෂයයි. මෙය ලංකාවට වැඩම කරවන ලද්දේ අශෝක අධිරාජ්‍යයාගේ දියණිය වූ සංඝමිත්තා රෙහෙණින් වහන්සේ විසිනි."
  },
  vatadageya: {
    EN: "The Polonnaruwa Vatadage is an ancient structure dating back to the Kingdom of Polonnaruwa. It is believed to have been built during the reign of Parakramabahu I to hold the Relic of the tooth of the Buddha, or during the reign of Nissanka Malla of Polonnaruwa to hold the alms bowl used by the Buddha. Both these sacred relics would have given the structure a great significance. Located in the center of the ancient city of Polonnaruwa, it is one of the best-preserved examples of a vatadage in the country.",
    SI: "පොළොන්නරුව වටදාගෙය යනු පොළොන්නරුව රාජධානි සමයට අයත් පැරණි ගොඩනැගිල්ලකි. මෙය පළමුවන පරාක්‍රමබාහු රජු හෝ නිශ්ශංක මල්ල රජු විසින් දන්ත ධාතූන් වහන්සේ හෝ පාත්‍ර ධාතූන් වහන්සේ තැන්පත් කිරීම සඳහා ඉදිකරන ලද බව විශ්වාස කෙරේ. පොළොන්නරුව පුරාණ නගරයේ මධ්‍යයේ පිහිටි මෙය රටේ ඇති හොඳම මට්ටමින් සංරක්ෂණය කර ඇති වටදාගෙයකි."
  },
  thuparamaya: {
    EN: "Thuparamaya is the first Buddhist council in Sri Lanka. Built by King Devanampiyatissa (247-207 BC), it is the first stupa to be built in the country after the introduction of Buddhism. The stupa houses the right collarbone relic of the Buddha. The name Thuparamaya comes from 'stupa' and 'aramaya' (monastery complex). The original shape was paddy-heap, but it was restored to a bell shape in 1862. The ruins of the stone pillars that once supported a roof over the stupa can still be seen.",
    SI: "ථූපාරාමය යනු ශ්‍රී ලංකාවේ ඉදිකරන ලද ප්‍රථම ස්තූපයයි. මෙය ක්‍රි.පූ. 247-207 කාලයේ දේවානම්පියතිස්ස රජු විසින් ඉදිකරන ලදී. මෙහි බුදුරජාණන් වහන්සේගේ දකුණු අකු ධාතුව තැන්පත් කර ඇත. ථූපාරාමය යන නාමය 'ථූප' සහ 'ආරාමය' යන වචන වලින් බිහිවී ඇත. මුලින් ධාන්‍යාකාර හැඩයෙන් යුක්ත වූ මෙය 1862 දී ඝණ්ඨාකාර හැඩයට ප්‍රතිසංස්කරණය කරන ලදී."
  },
  abhayagiriya: {
    EN: "Abhayagiri Vihara was a major monastery site of Mahayana, Theravada and Vajrayana Buddhism that was situated in Anuradhapura. It is one of the most extensive ruins in the world and one of the most sacred Buddhist pilgrimage cities in the nation. Historically it was a great monastic center as well as a royal capital, with magnificent stupas. The Abhayagiri Dagaba was the second largest stupa in the world at the time of its completion, standing at 75 m (246 ft) high.",
    SI: "අභයගිරි විහාරය යනු අනුරාධපුරයේ පිහිටි මහායාන, ථෙරවාද සහ වජ්‍රයාන බුදුදහමේ ප්‍රධාන මධ්‍යස්ථානයකි. මෙය ලොව ඇති විශාලතම නටබුන් සහිත ස්ථානවලින් එකක් වන අතර පූජනීය වන්දනා නගරයකි. අභයගිරි දාගැබ ඉදිකර අවසන් වූ සමයේ ලොව දෙවන විශාලතම ස්තූපය වූ අතර එය මීටර් 75 ක් පමණ උසින් යුක්ත විය."
  },
  jetavanaramaya: {
    EN: "The Jetavanaramaya is a stupa located in the ruins of Jetavana monastery in the UNESCO world heritage city of Anuradhapura. At 122 metres (400 ft), it was the world's tallest stupa and the third tallest structure in the world when it was built by King Mahasen (273–301 AD). It is also the largest brick building ever built. The structure is significant in the island's history as it represents the tensions within the Theravada and Mahayana sects of Buddhism.",
    SI: "ජේතවනාරාමය යනු අනුරාධපුරයේ පිහිටි දැවැන්ත ස්තූපයකි. මීටර් 122 ක් උසැති මෙය ඉදිකරන සමයේ ලොව උසම ස්තූපය සහ ලොව තෙවන උසම ගොඩනැගිල්ල විය. මෙය මහසෙන් රජු විසින් ඉදිකරන ලදී. මෙය ලොව මෙතෙක් ඉදිකරන ලද විශාලතම ගඩොල් ගොඩනැගිල්ල ද වේ."
  },
  "gal-vihara": {
    EN: "Gal Vihara, also known as Uttararama, is a rock temple of the Buddha situated in the ancient city of Polonnaruwa. It was fashioned in the 12th century by King Parakramabahu I. The central feature of the temple is four rock relief statues of the Buddha, which have been carved into the face of a large granite rock. The images consist of a large seated figure, another smaller seated figure inside an artificial cavern, a standing figure and a reclining figure. These are considered to be some of the best examples of ancient Sinhalese sculpting and carving arts.",
    SI: "ගල් විහාරය හෙවත් උත්තරාරාමය යනු පොළොන්නරුව පුරාණ නගරයේ පිහිටි ශිලා විහාරයකි. මෙය 12 වන සියවසේදී පළමුවන පරාක්‍රමබාහු රජු විසින් කරවන ලදී. මෙහි ඇති ප්‍රධාන ආකර්ෂණය වන්නේ තනි කළු ගලක නෙළන ලද විශිෂ්ට බුදු පිළිම හතරයි. මෙහි හිඳි පිළිම දෙකක්, හිටි පිළිමයක් සහ සැතපෙන පිළිමයක් දැකගත හැකිය. මේවා පැරණි සිංහල කැටයම් කලාවේ විශිෂ්ටතම නිර්මාණ ලෙස සැලකේ."
  },
  "lankatilaka-vihara": {
    EN: "The Lankatilaka Vihara is an ancient structure in the city of Polonnaruwa. Built by King Parakramabahu I, it is a massive brick building that originally stood five stories high. The most striking feature is the giant headless Buddha statue that stands inside the shrine. The walls of the building are decorated with intricate carvings and paintings. The structure is a fine example of the 'gedige' style of architecture, which features thick brick walls and a vaulted roof.",
    SI: "ලංකාතිලක විහාරය යනු පොළොන්නරුව පුරාණ නගරයේ පිහිටි පැරණි ගොඩනැගිල්ලකි. පළමුවන පරාක්‍රමබාහු රජු විසින් ඉදිකරන ලද මෙය මහල් පහකින් යුක්ත වූ දැවැන්ත ගඩොල් ගොඩනැගිල්ලකි. මෙහි ඇති සුවිශේෂී ලක්ෂණය වන්නේ ඇතුළත ඇති යෝධ හිස රහිත බුදු පිළිමයයි. මෙය 'ගෙඩිගේ' වාස්තු විද්‍යා ශෛලියට කදිම උදාහරණයකි."
  },
  "galle-fort": { 
    EN: "Galle Fort, in the Bay of Galle on the southwest coast of Sri Lanka, was built first in 1588 by the Portuguese, then extensively fortified by the Dutch during the 17th century from 1649 onwards. It is a historical, archaeological and architectural heritage monument, which even after more than 432 years maintains a polished appearance, due to extensive reconstruction work done by the Archaeological Department of Sri Lanka. The fort has a colourful history, and today has a multi-ethnic and multi-religious population. The heritage value of the fort has been recognized by the UNESCO and the site has been inscribed as a cultural heritage UNESCO World Heritage Site. It is a 'living' heritage site, with a bustling community living within its ramparts. Key landmarks include the Dutch Reformed Church, the Old Dutch Hospital, the Galle Lighthouse, and the massive ramparts that offer stunning views of the Indian Ocean. The narrow cobblestone streets are lined with colonial-era buildings, many of which have been converted into boutique hotels, shops, and cafes.", 
    SI: "ශ්‍රී ලංකාවේ නිරිතදිග වෙරළ තීරයේ ගාල්ල බොක්කෙහි පිහිටි ගාල්ල කොටුව ප්‍රථමයෙන් 1588 දී පෘතුගීසීන් විසින් ඉදිකරන ලද අතර පසුව 17 වන සියවසේදී ලන්දේසීන් විසින් විශාල වශයෙන් ශක්තිමත් කරන ලදී. මෙය වසර 432 කට වඩා පැරණි වුවද ශ්‍රී ලංකා පුරාවිද්‍යා දෙපාර්තමේන්තුව විසින් සිදු කරන ලද ප්‍රතිසංස්කරණ කටයුතු හේතුවෙන් අදටත් මනාව පවතී. කොටුව සතුව වර්ණවත් ඉතිහාසයක් ඇති අතර අද වන විට එහි විවිධ ජාතීන් හා ආගම් වලට අයත් ජනතාවක් ජීවත් වෙති. මෙහි ඇති ඓතිහාසික වටිනාකම නිසා යුනෙස්කෝව විසින් මෙය ලෝක උරුමයක් ලෙස නම් කර ඇත. ලන්දේසි ප්‍රතිසංස්කරණ පල්ලිය, පැරණි ලන්දේසි රෝහල, ගාල්ල ප්‍රදීපාගාරය සහ ඉන්දියන් සාගරයේ මනරම් දර්ශන ලබා දෙන දැවැන්ත පවුර මෙහි ඇති ප්‍රධාන සන්ධිස්ථාන වේ. පටු ගල් අතුරා ඇති වීදි දිගේ යටත් විජිත යුගයේ ගොඩනැගිලි පිහිටා ඇති අතර ඒවායින් බොහොමයක් අද වන විට හෝටල්, වෙළඳසැල් සහ ආපනශාලා බවට පත් කර ඇත." 
  },
  dambulla: { 
    EN: "Dambulla Cave Temple, also known as the Golden Temple of Dambulla, is a World Heritage Site in Sri Lanka, situated in the central part of the country. Dambulla is the largest and best-preserved cave temple complex in Sri Lanka. The rock towers 160 m over the surrounding plains. There are more than 80 documented caves in the surrounding area. Major attractions are spread over five caves, which contain statues and paintings. These paintings and statues are related to Gautama Buddha and his life. There are a total of 153 Buddha statues, three statues of Sri Lankan kings and four statues of gods and goddesses. The murals cover an area of 2,100 square metres (23,000 sq ft). Depictions on the walls of the caves include the temptation by the demon Mara and Buddha's first sermon. The history of the temple dates back to the 1st century BC, when King Valagamba took refuge here and later converted the caves into a magnificent temple complex in gratitude.", 
    SI: "දඹුලු ලෙන් විහාරය හෙවත් දඹුල්ලේ රන් විහාරය යනු ශ්‍රී ලංකාවේ මධ්‍යම ප්‍රදේශයේ පිහිටි ලෝක උරුම ස්ථානයකි. මෙය ශ්‍රී ලංකාවේ විශාලතම හා හොඳම මට්ටමින් සංරක්ෂණය කර ඇති ලෙන් විහාර සංකීර්ණයයි. අවට තැන්නෙන් මීටර් 160 ක් පමණ උසට පර්වතය විහිදී ඇත. අවට ප්‍රදේශයේ ලේඛනගත කරන ලද ලෙන් 80 කට වඩා තිබේ. ප්‍රධාන ආකර්ෂණීය ස්ථාන ලෙන් පහක් පුරා පැතිරී ඇති අතර ඒවායේ බුදු පිළිම සහ සිතුවම් අඩංගු වේ. මෙම සිතුවම් සහ පිළිම ගෞතම බුදුරජාණන් වහන්සේ සහ උන්වහන්සේගේ ජීවිතයට සම්බන්ධ වේ. මෙහි බුදු පිළිම 153 ක්, ශ්‍රී ලාංකේය රජවරුන්ගේ පිළිම 3 ක් සහ දෙවි දේවතාවුන්ගේ පිළිම 4 ක් ඇත. බිතුසිතුවම් වර්ග මීටර් 2,100 ක ප්‍රදේශයක් පුරා විහිදී පවතී. මෙම විහාරයේ ඉතිහාසය ක්‍රි.පූ. 1 වන සියවස දක්වා දිවයන අතර, වළගම්බා රජු සතුරන්ගෙන් බේරී මෙහි සැඟවී සිට පසුව කෘතගුණ සැලකීමක් ලෙස මෙම ලෙන් විහාර සංකීර්ණයක් බවට පත් කළේය." 
  },
  "kandy-temple": { 
    EN: "The Temple of the Sacred Tooth Relic, commonly known as Sri Dalada Maligawa, is a Buddhist temple in the city of Kandy, Sri Lanka. It is located in the royal palace complex of the former Kingdom of Kandy, which houses the relic of the tooth of the Buddha. Since ancient times, the relic has played an important role in local politics because it is believed that whoever holds the relic holds the governance of the country. Kandy was the last capital of the Sri Lankan kings and is a World Heritage Site mainly due to the temple. The temple architecture is a unique blend of traditional Kandyan styles, featuring intricate wood carvings, painted ceilings, and silver-embossed doors. The Paththirippuwa (Octagon), built by the last king of Kandy, is an iconic part of the complex. Every year, the Esala Perahera, one of the oldest and grandest Buddhist festivals in the world, features a magnificent procession where the sacred relic is paraded through the streets of Kandy on a majestic tusker.", 
    SI: "ශ්‍රී දන්ත ධාතු මන්දිරය හෙවත් ශ්‍රී දළදා මාළිගාව යනු ශ්‍රී ලංකාවේ මහනුවර නගරයේ පිහිටි බෞද්ධ විහාරස්ථානයකි. මෙය බුදුරජාණන් වහන්සේගේ ශ්‍රී දන්ත ධාතූන් වහන්සේ වැඩසිටින පැරණි මහනුවර රාජධානියේ රාජකීය මාලිගා සංකීර්ණය තුළ පිහිටා ඇත. පුරාණ කාලයේ සිටම දන්ත ධාතූන් වහන්සේ දේශපාලනික වශයෙන් වැදගත් කාර්යභාරයක් ඉටු කර ඇති අතර, දන්ත ධාතූන් වහන්සේගේ හිමිකාරිත්වය දරන තැනැත්තාට රටේ පාලන බලය හිමිවන බවට විශ්වාසයක් පවතී. මහනුවර යනු ශ්‍රී ලාංකේය රජවරුන්ගේ අවසාන අගනුවර වූ අතර මෙම විහාරස්ථානය නිසාම එය ලෝක උරුමයක් බවට පත්ව ඇත. විහාරයේ වාස්තු විද්‍යාව සාම්ප්‍රදායික උඩරට ශෛලීන්ගේ අද්විතීය සම්මිශ්‍රණයක් වන අතර සංකීර්ණ ලී කැටයම්, සිතුවම් කළ සිවිලිම් සහ රිදී කැටයම් කළ දොරවල් මෙහි දැකගත හැකිය. මහනුවර අවසාන රජු විසින් ඉදිකරන ලද පත්තිරිප්පුව මෙම සංකීර්ණයේ සුවිශේෂී කොටසකි. සෑම වසරකම ලොව පැරණිතම හා උදාරතම බෞද්ධ උත්සවයක් වන ඇසළ පෙරහැරේදී දන්ත ධාතූන් වහන්සේ වීදි සංචාරය කරවනු ලබයි." 
  },
  mihintale: { 
    EN: "Mihintale is a mountain peak near Anuradhapura in Sri Lanka. It is believed by Sri Lankans to be the site of a meeting between the Buddhist monk Mahinda and King Devanampiyatissa which inaugurated the presence of Buddhism in Sri Lanka. It is now a pilgrimage site, and the site of several religious monuments and abandoned structures. The climb to the summit involves ascending 1,840 ancient granite steps, passing through several levels of historical significance. Key sites include the Ambasthala Dagaba, built where the meeting is said to have occurred, the massive Maha Stupa at the summit, and the Kantaka Cetiya with its exquisite stone carvings. The Kaludiya Pokuna (Black Water Pond) and the ancient hospital ruins at the foot of the mountain reflect the advanced civilization that thrived here. Mihintale is especially vibrant during the Poson Poya festival in June, when thousands of devotees gather to commemorate the arrival of Buddhism.", 
    SI: "මිහින්තලේ යනු ශ්‍රී ලංකාවේ අනුරාධපුරයට ආසන්නව පිහිටි කඳු මුදුනකි. මෙය මහින්ද රහතන් වහන්සේ සහ දේවානම්පියතිස්ස රජු අතර හමුවීම සිදු වූ ස්ථානය ලෙස ශ්‍රී ලාංකිකයන් විශ්වාස කරන අතර එමඟින් ශ්‍රී ලංකාවට බුදුදහම හඳුන්වා දෙන ලදී. අද වන විට මෙය වන්දනාමාන කරන ස්ථානයක් වන අතර ආගමික ස්මාරක සහ පැරණි ගොඩනැගිලි රැසක් මෙහි පිහිටා ඇත. කඳු මුදුනට පිවිසීම සඳහා පැරණි කළු ගලින් නිමවූ පඩි 1,840 ක් තරණය කළ යුතු අතර, ඒ අතරතුර ඓතිහාසික වටිනාකමකින් යුත් ස්ථාන රැසක් පසු කිරීමට සිදු වේ. අඹස්තල දාගැබ, කඳු මුදුනේ ඇති මහා ස්තූපය සහ විශිෂ්ට ගල් කැටයම් සහිත කණ්ඨක චේතිය මෙහි ඇති ප්‍රධාන ස්ථාන වේ. කන්ද පාමුල ඇති කළුදිය පොකුණ සහ පැරණි රෝහල් නටබුන් මෙහි පැවති දියුණු ශිෂ්ටාචාරය විදහා දක්වයි. ජූනි මාසයේ පැවැත්වෙන පොසොන් පොය උත්සවයේදී බුදුදහමේ පැමිණීම සැමරීම සඳහා දහස් සංඛ්‍යාත බැතිමතුන් මිහින්තලයට රැස් වෙති." 
  },
  yapahuwa: { 
    EN: "Yapahuwa was one of the ephemeral capitals of medieval Sri Lanka. The citadel of Yapahuwa, lying midway between Kurunegala and Anuradhapura, was built around a huge granite rock rising abruptly nearly a hundred meters above the surrounding lowlands. In 1272, King Bhuvanekabahu I transferred the capital to Yapahuwa and brought the Sacred Tooth Relic here. The most remarkable feature of Yapahuwa is the magnificent ornamental staircase that leads to the terrace where the Tooth Relic was once housed. This staircase is decorated with intricate stone carvings of lions, dancers, musicians, and mythical creatures, reflecting a high level of artistic achievement. The style is notably influenced by South Indian architectural traditions. Although the capital was short-lived, falling to a Pandyan invasion in 1284, the ruins of the fortress, caves, and temples remain as a testament to its former glory. The view from the top of the rock offers a panoramic vista of the surrounding countryside.", 
    SI: "යාපහුව යනු මධ්‍යතන යුගයේ ශ්‍රී ලංකාවේ කෙටි කාලීන අගනුවරකි. කුරුණෑගල සහ අනුරාධපුරය අතර පිහිටි යාපහුව බලකොටුව, අවට තැන්නෙන් මීටර් සියයක් පමණ උසට විහිදෙන දැවැන්ත කළු ගල් පර්වතයක් වටා ගොඩනගා ඇත. ක්‍රි.ව. 1272 දී පළමුවන බුවනෙකබාහු රජු සිය අගනුවර යාපහුවට මාරු කළ අතර ශ්‍රී දන්ත ධාතූන් වහන්සේ ද මෙහි වැඩම කරවන ලදී. යාපහුවේ වඩාත්ම කැපී පෙනෙන ලක්ෂණය වන්නේ දන්ත ධාතූන් වහන්සේ තැන්පත් කර තිබූ මළුව වෙත දිවෙන අලංකාර කැටයම් සහිත පඩිපෙළයි. මෙම පඩිපෙළ සිංහයන්, නර්තන ශිල්පීන්, සංගීතඥයන් සහ මිථ්‍යා සත්වයන්ගේ සංකීර්ණ ශිලා කැටයම් වලින් සරසා ඇති අතර එය උසස් කලාත්මක කුසලතාවක් විදහා දක්වයි. ක්‍රි.ව. 1284 දී පාණ්ඩ්‍ය ආක්‍රමණයකින් මෙම අගනුවර බිඳ වැටුණද, බලකොටුවේ නටබුන්, ලෙන් සහ විහාරස්ථාන එහි පැරණි අභිමානයට සාක්ෂි දරයි." 
  },
  ritigala: { 
    EN: "Ritigala is an ancient Buddhist monastery and mountain range in North Central Sri Lanka. The ruins and rock inscriptions of the monastery date back to the 1st century BC. It is located 43 km away from the ancient city of Anuradhapura. The mountain range consists of four peaks, with the highest point being 766 meters above sea level. Ritigala is unique because of its microclimate; the higher elevations are much cooler and support vegetation that is otherwise found only in the central highlands. The monastery is a prime example of the 'Pansukulika' tradition, where monks lived in simple, austere settings focused on meditation. The ruins include massive stone-paved paths, sunken courtyards, and unique double-platform structures (padhanaghara) surrounded by moats. There are no stupas or statues here, reflecting the monks' focus on internal spiritual practice. The site is also associated with legends from the Ramayana, believed to be a place where Hanuman dropped medicinal herbs from the Himalayas.", 
    SI: "රිටිගල යනු උතුරු මැද ශ්‍රී ලංකාවේ පිහිටි පැරණි බෞද්ධ ආරාමයක් සහ කඳු පන්තියකි. මෙහි නටබුන් සහ ශිලා ලේඛන ක්‍රි.පූ. 1 වන සියවස දක්වා දිවයයි. මෙය අනුරාධපුර පුරාණ නගරයේ සිට කිලෝමීටර් 43 ක් දුරින් පිහිටා ඇත. රිටිගල කඳු පන්තිය කඳු මුදුන් හතරකින් සමන්විත වන අතර එහි උසම ස්ථානය මුහුදු මට්ටමේ සිට මීටර් 766 කි. රිටිගල සතු සුවිශේෂී දේශගුණය නිසා මධ්‍යම කඳුකරයේ පමණක් දැකිය හැකි ශාක මෙහි දැකගත හැකිය. භාවනාවට මුල්තැන දෙමින් සරල දිවියක් ගත කළ පාංශුකූලික භික්ෂූන් වහන්සේලාගේ ආරාම සම්ප්‍රදායට මෙය කදිම උදාහරණයකි. ගල් අතුරා ඇති මාවත්, ගිලුණු මළුවවල් සහ අගල් වලින් වට වූ ද්විත්ව වේදිකා (පධානඝර) මෙහි නටබුන් අතර වේ. මෙහි ස්තූප හෝ පිළිම නොමැති වීම භික්ෂූන් වහන්සේලාගේ ආධ්‍යාත්මික පුහුණුව කෙරෙහි වූ අවධානය විදහා දක්වයි. රාමායණ පුවතට අනුව හනුමාන් විසින් හිමාලයෙන් රැගෙන ආ ඔසු පැළෑටි වැටුණු ස්ථානයක් ලෙස ද රිටිගල සැලකේ." 
  },
  buduruwagala: { 
    EN: "Buduruwagala is an ancient Buddhist temple in Sri Lanka. The complex consists of seven statues and belongs to the Mahayana school of thought. The statues date back to the 10th century. The gigantic standing Buddha statue is the tallest in Sri Lanka, reaching a height of 16 meters (51 ft). It still bears traces of its original stuccoed robe and a streak of orange suggests that it was once brightly painted. The central Buddha statue is flanked by two groups of three statues. On the Buddha's right is a group led by Avalokitesvara, the Bodhisattva of Compassion, identified by the small Buddha figure in his headdress. To the left is another group featuring Maitreya, the future Buddha, and Vajrapani. One of the most intriguing features is a carved alcove that is constantly moist with an oil-like substance that smells of mustard oil, the source of which remains a mystery. The name Buduruwagala means 'the rock of Buddhist sculptures'. The site is set in a peaceful environment surrounded by a large reservoir and lush forest.", 
    SI: "බුදුරුවගල යනු ශ්‍රී ලංකාවේ පිහිටි පැරණි බෞද්ධ විහාරස්ථානයකි. පිළිම හතකින් සමන්විත මෙම සංකීර්ණය මහායාන බුදුදහමට අයත් වන අතර ඒවා 10 වන සියවසට අයත් වේ. මෙහි ඇති දැවැන්ත හිටි බුදු පිළිමය මීටර් 16 ක් (අඩි 51 ක්) උස වන අතර එය ශ්‍රී ලංකාවේ උසම බුදු පිළිමයයි. ප්‍රධාන බුදු පිළිමයට දෙපසින් පිළිම තුන බැගින් වූ කණ්ඩායම් දෙකක් ඇත. බුදුරජාණන් වහන්සේගේ දකුණු පසින් අවලෝකිතේශ්වර බෝධිසත්වයන් ප්‍රමුඛ කණ්ඩායම ද, වම් පසින් මෛත්‍රී බෝධිසත්වයන් සහ වජ්‍රපාණි ප්‍රමුඛ කණ්ඩායම ද පිහිටා ඇත. මෙහි ඇති වඩාත්ම කුතුහලය දනවන ලක්ෂණය වන්නේ අබ තෙල් සුවඳ විහිදෙන, නිරන්තරයෙන් තෙතමනය සහිතව පවතින ශිලා කුහරයකි. මෙහි තෙතමනය ඇතිවීමට හේතුව අදටත් අභිරහසකි. බුදුරුවගල යන නාමයේ අර්ථය 'බුදු පිළිම සහිත ගල' යන්නයි. විශාල වැවකින් සහ වනාන්තරයකින් වට වූ ඉතා සාමකාමී පරිසරයක මෙම ස්ථානය පිහිටා ඇත." 
  },

  // Beaches
  unawatuna: { EN: "A beautiful beach with golden sand and calm blue water.", SI: "රන්වන් වැලි සහ නිල්වන් සාගරය සහිත අඩ සඳක හැඩැති වෙරළකි." },
  mirissa: { EN: "A great place to see whales and take photos of palm trees.", SI: "තල්මසුන් නැරඹීම සහ කොකනට් ට්‍රී හිල් නිසා ප්‍රසිද්ධය." },
  hikkaduwa: { EN: "A fun beach town with coral reefs and sea turtles.", SI: "කොරල් පර සහ මුහුදු කැස්බෑවන් නිසා ප්‍රසිද්ධ සංචාරක නගරයකි." },
  arugambay: { EN: "One of the best places in the world to surf.", SI: "ලොව හොඳම සර්ෆින් ස්ථානයක් වන අතර මෙය ඉතා නිදහස් පරිසරයකි." },
  bentota: { EN: "A top place for water sports where the river meets the sea.", SI: "ගඟ සහ මුහුද හමුවන ස්ථානයේ පිහිටි ජල ක්‍රීඩා පාරාදීසයකි." },
  nilaveli: { EN: "A quiet beach with clear water and white sand.", SI: "පැහැදිලි නිල්වන් සාගරය සහ සුදු වැලි සහිත නිහඬ වෙරළකි." },
  pasikudah: { EN: "A beach with very shallow water and natural pools.", SI: "නොගැඹුරු මුහුද සහ ස්වභාවික කොරල් තටාක නිසා ප්‍රසිද්ධය." },
  tangalle: { EN: "A peaceful place by the sea to relax.", SI: "ඉන්දියන් සාගරයේ කෙළවර පිහිටි ඉතා සාමකාමී නවාතැනකි." },
  weligama: { EN: "A sandy village famous for surfing and fishing.", SI: "රිටි පන්න ක්‍රමය සහ සර්ෆින් නිසා ප්‍රසිද්ධ වැලිගම වෙරළ." },
  kalpitiya: { EN: "A great beach for kite surfing and seeing dolphins.", SI: "කයිට් සර්ෆින් සහ ඩොල්ෆින් නැරඹීමට හොඳම ස්ථානය කල්පිටියයි." },

  // Wildlife
  yala: { EN: "A big park where you can see many leopards.", SI: "දිවියන්ගේ රාජධානිය වන මෙය ලංකාවේ ප්‍රසිද්ධම වනෝද්‍යානයයි." },
  udawalawe: { EN: "The best place to see wild elephants in nature.", SI: "වන අලි නැරඹීමට ආසියාවේ ඇති හොඳම ස්ථානය උඩවලවයි." },
  minneriya: { EN: "A place where hundreds of wild elephants meet.", SI: "ලොව විශාලතම වන අලි රංචු ගැසීම සිදුවන ස්ථානයයි." },
  wilpattu: { EN: "The largest park in Sri Lanka with many natural lakes.", SI: "ස්වභාවික විල් වලින් පිරි ලංකාවේ විශාලතම වනෝද්‍යානයයි." },
  kumana: { EN: "A quiet place for birds in the East.", SI: "නැගෙනහිර පිහිටි හුදකලා පක්ෂි පාරාදීසයක් සහ විල්ලු පද්ධතියකි." },
  bundala: { EN: "A park by the sea famous for beautiful birds.", SI: "වෙරළබඩ කලපුවලින් පිරි මෙහි සංචාරක පක්ෂීන් බහුලව දැකගත හැක." },
  sinharaja: { EN: "A very old and beautiful rainforest with many animals.", SI: "ලෝක උරුමයක් වන මෙය ඉතා වටිනා වැසි වනාන්තරයකි." },
  horton: { EN: "A high park with a famous cliff called World's End.", SI: "මීදුමෙන් වැසුණු කඳුකර තැන්නක් වන මෙහි ලෝකාන්තය පිහිටා ඇත." },
  pigeonisland: { EN: "A park in the sea with coral reefs and sharks.", SI: "කොරල් පර සහ මෝරුන් නැරඹිය හැකි මුහුදු උද්‍යානයකි." },
  wasgamuwa: { EN: "A wild place where bears and elephants live.", SI: "වලසුන් සහ අලි ඇතුන් සැරිසරන හුදකලා වනාන්තරයකි." },

  // Mountains
  ella: { EN: "A beautiful village with tea farms and a famous bridge.", SI: "තේ වතු සහ ආරුක්කු නවය පාලම සහිත සුන්දර කඳුකර ගම්මානයකි." },
  nuwaraeliya: { EN: "A cool town in the hills with old British buildings.", SI: "බ්‍රිතාන්‍ය ගෘහ නිර්මාණ ශිල්පය සහිත සිසිල් කඳුකර නගරයකි." },
  "adam'speak": { EN: "A holy mountain that many people climb for prayer.", SI: "පූජනීය කඳු මුදුනක් වන මෙය වන්දනාකරුවන්ගේ ගමනාන්තයකි." },
  knuckles: { EN: "A group of mountains great for walking and camping.", SI: "කඳු තරණයට සහ කඳවුරු බැඳීමට සුදුසුම දුෂ්කර කඳු පන්තියකි." },
  haputale: { EN: "A town in the hills with amazing views of the land below.", SI: "තැන්න දක්වා දිවෙන මනරම් දර්ශන සහිත මීදුම් පිරි කඳු ගැටයකි." },
  bandarawela: { EN: "A nice town with good weather and old charm.", SI: "සුවදායී දේශගුණයක් සහිත පැරණි බ්‍රිතාන්‍ය ලක්ෂණ පිරි නගරයකි." },
  badulla: { EN: "A main town in the hills at the end of the train line.", SI: "ඌව කඳුකරයේ ප්‍රධාන නගරය සහ දුම්රිය මගේ අවසානයයි." },
  hatton: { EN: "A town famous for tea and the start of the climb to Adam's Peak.", SI: "තේ කර්මාන්තයේ මධ්‍යස්ථානය සහ සිරිපා පිවිසුමයි." },
  pidurangala: { EN: "A hill with the best view of the Sigiriya rock.", SI: "සීගිරි බලකොටුව නැරඹීමට ඇති හොඳම ස්ථානයයි." },
  riverston: { EN: "A windy place in the hills with cliffs and waterfalls.", SI: "දැඩි සුළඟ සහ මනරම් දියඇලි සහිත කඳුකර මංකඩකි." },

  // Waterfalls
  diyaluma: { EN: "The second highest waterfall in Sri Lanka with pools to swim.", SI: "ලංකාවේ දෙවන උසම දියඇල්ල වන මෙය ස්වභාවික තටාකවලින් පිරි ඇත." },
  bambarakanda: { EN: "The highest waterfall in Sri Lanka.", SI: "ලංකාවේ උසම දියඇල්ලයි. මෙය මීටර් 263 ක් උසය." },
  ravanafalls: { EN: "A wide waterfall from a famous old story.", SI: "රාම රාවණා කතාව සමඟ බැඳුණු පුළුල් දියඇල්ලකි." },
  dunhinda: { EN: "A beautiful waterfall that looks like mist.", SI: "මීදුමක් ලෙස විසිරෙන දිය දහර නිසා ප්‍රසිද්ධ දුන්හිඳ ඇල්ල." },
  "baker'sfalls": { EN: "A very cold waterfall in the high plains.", SI: "හෝර්ටන් තැන්න ඇතුළත පිහිටි ඉතා සිසිල් දියඇල්ලකි." },
  "stclair's": { EN: "A wide waterfall in the middle of green tea farms.", SI: "තේ වතු මැදින් ගලා යන ලංකාවේ පුළුල්ම දියඇල්ලකි." },
  devonfalls: { EN: "A beautiful waterfall you can see from the road.", SI: "ප්‍රධාන මාර්ගයට පෙනෙන ඉතා මනරම් දියඇල්ලකි." },
  bopathella: { EN: "A waterfall shaped like a leaf.", SI: "බෝ පතක හැඩය ගන්නා සුවිශේෂී දියඇල්ලකි." },
  laxapana: { EN: "A strong waterfall used to make power.", SI: "විදුලිය නිපදවීමට දායක වන ප්‍රබල දියඇල්ලකි." },
  aberdeen: { EN: "A hidden waterfall in a quiet valley.", SI: "කඳුකර නිම්නයක සැඟවී ඇති සුන්දර දියඇල්ලකි." },

  // Camping
  "knuckles-camp": { EN: "Camping in a wild forest with many clouds.", SI: "මීදුම් වනාන්තරය මැද වනගත කඳවුරු අත්දැකීමකි." },
  "kumana-camp": { EN: "Sleep under the stars near the water in the East.", SI: "නැගෙනහිර විල්ලු අසල තරු පිරි අහස යට නින්දක්." },
  "horton-camp": { EN: "Camping in a high place that is very cold at night.", SI: "අධික සීතල සහිත ඉහළ කඳුකරයේ කඳවුරු අත්දැකීමකි." },
  belihuloya: { EN: "Camping by a clear mountain river.", SI: "පැහැදිලි දිය දහර අසල කඳුකර කඳවුරු බැඳීම." },
  ellacamp: { EN: "Camping in the jungle with great views of the hills.", SI: "ඇල්ල නිම්නයේ දර්ශන සහිත වනාන්තර කඳවුරක්." },
  kitulgala: { EN: "Camping by a river for fun and adventure.", SI: "කැලණි ගඟ අසල වික්‍රමාන්විත කඳවුරු බැඳීම." },
  meemure: { EN: "Camping in a far-away village near the mountains.", SI: "නකල්ස් පාමුල හුදකලා ගම්මානයක කඳවුරු බැඳීම." },
  yalablock2: { EN: "A wild camp deep in the forest of the south.", SI: "දකුණු වනගැඹුරේ විඳිය හැකි හොඳම කඳවුරු අත්දැකීම." },
  maduruoya: { EN: "Camping by a lake in an old kingdom.", SI: "පැරණි වාරි රාජධානියක වැව් ඉවුරේ කඳවුරු බැඳීම." },
  peakcamp: { EN: "Camping in a holy place high in the mountains.", SI: "සිරිපා රක්ෂිතයේ පූජනීය කඳුකර කඳවුරු බැඳීම." }
};

export const LOGISTICS_DATA: Record<string, { EN: string, SI: string }> = {
  ruwanwelisaya: { EN: "Access via A12 or A9. 200 km from Colombo. Best visited early morning.", SI: "A12 හෝ A9 මාර්ගයෙන් පැමිණිය හැක. උදෑසන කාලය වඩාත් සුදුසුයි." },
  "jaya-sri-maha-bodhi": { EN: "Located in Mahamewna Gardens. Dress in white.", SI: "මහමෙව්නා උයනේ පිහිටා ඇත. සුදු ඇඳුමෙන් සැරසී එන්න." },
  vatadageya: { EN: "Located in the Quadrangle, Polonnaruwa. 220 km from Colombo.", SI: "පොළොන්නරුව දළදා මළුවේ පිහිටා ඇත." },
  thuparamaya: { EN: "Near Ruwanwelisaya. Walking distance.", SI: "රුවන්වැලිසෑයට ආසන්නව පිහිටා ඇත." },
  abhayagiriya: { EN: "Northern part of Anuradhapura. Large complex.", SI: "අනුරාධපුර උතුරු ප්‍රදේශයේ පිහිටා ඇත." },
  jetavanaramaya: { EN: "East of Ruwanwelisaya. Massive structure.", SI: "රුවන්වැලිසෑයට නැගෙනහිරින් පිහිටා ඇත." },
  "gal-vihara": { EN: "Northern end of Polonnaruwa. 4WD not needed.", SI: "පොළොන්නරුව උතුරු කෙළවරේ පිහිටා ඇත." },
  "lankatilaka-vihara": { EN: "Near Gal Vihara. Impressive brickwork.", SI: "ගල් විහාරයට ආසන්නව පිහිටා ඇත." },
  yala: { EN: "Safari starts at 6 AM. 4WD vehicle required.", SI: "සෆාරි ගමන උදෑසන 6 ට ඇරඹේ. ජීප් රථයක් අවශ්‍යයි." },
  ella: { EN: "Reach via train or A16 road. Cool climate.", SI: "දුම්රියෙන් හෝ A16 මාර්ගයෙන් පැමිණිය හැක." },
  "galle-fort": { EN: "Southern Expressway access. 2 hours from Colombo.", SI: "දක්ෂිණ අධිවේගී මාර්ගයෙන් පැය 2 කි." }
};
